import { StyleSheet } from "react-native";
import { COLORS, RADIUS, SHADOWS, SPACING, FONTS } from "../../design";
export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  content: { padding: SPACING.lg, paddingBottom: SPACING.xxxl },
  compactContent: { paddingHorizontal: SPACING.lg, paddingBottom: SPACING.xxxl },
  hero: { alignItems: "center", marginBottom: SPACING.xl },
  heroIcon: { width: 88, height: 88, borderRadius: 44, alignItems: "center", justifyContent: "center", backgroundColor: COLORS.primaryLight, marginBottom: SPACING.md },
  title: { color: COLORS.text, fontSize: 26, fontFamily: FONTS.display, fontWeight: "normal", lineHeight: 32, textAlign: "center" },
  subtitle: { marginTop: SPACING.sm, color: COLORS.textSecondary, fontSize: 15, lineHeight: 22, textAlign: "center" },
  sectionTitle: { color: COLORS.text, fontSize: 18, fontFamily: FONTS.display, fontWeight: "normal", marginBottom: SPACING.md, marginTop: SPACING.md },
  card: { backgroundColor: COLORS.white, borderRadius: RADIUS.lg, borderWidth: 1, borderColor: COLORS.border, padding: SPACING.md, marginBottom: SPACING.md, ...SHADOWS.small },
  protocolCard: { backgroundColor: COLORS.white, borderRadius: RADIUS.xl, padding: SPACING.lg, borderWidth: 1, borderColor: COLORS.border, ...SHADOWS.medium },
  protocolTitle: { color: COLORS.text, fontSize: 25, lineHeight: 31, fontFamily: FONTS.display, fontWeight: "normal" },
  protocolText: { color: COLORS.text, fontSize: 17, lineHeight: 26, marginTop: SPACING.md },
  warningBox: { marginTop: SPACING.md, padding: SPACING.md, borderRadius: RADIUS.md, backgroundColor: COLORS.warningTint, borderWidth: 1, borderColor: COLORS.warning },
  warningText: { color: COLORS.text, fontWeight: "600", lineHeight: 21 },
  noteBox: { marginTop: SPACING.md, padding: SPACING.md, borderRadius: RADIUS.md, backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.border },
  noteText: { color: COLORS.textSecondary, lineHeight: 20 },
  actions: { marginTop: SPACING.lg, gap: SPACING.sm },
  button: { borderRadius: RADIUS.md },
  emergencyButton: { borderRadius: RADIUS.md, backgroundColor: COLORS.error },
  label: { color: COLORS.textSecondary, fontSize: 13, fontWeight: "700", marginBottom: SPACING.xs },
  value: { color: COLORS.text, fontSize: 15, lineHeight: 21 },
  row: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: SPACING.md },
  rowStart: { flexDirection: "row", alignItems: "center", gap: SPACING.sm },
  flex: { flex: 1 },
  badge: { paddingHorizontal: SPACING.sm, paddingVertical: 5, borderRadius: RADIUS.round, backgroundColor: COLORS.primaryLight },
  badgeText: { color: COLORS.primaryDark, fontWeight: "700", fontSize: 12 },
  dangerText: { color: COLORS.error, fontWeight: "700" },
  successText: { color: COLORS.success, fontWeight: "700" },
  input: { marginBottom: SPACING.md },
  muted: { color: COLORS.textSecondary, lineHeight: 20 },
  listItem: { paddingVertical: SPACING.sm, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  listTitle: { color: COLORS.text, fontSize: 15, fontWeight: "700" },
  listDescription: { marginTop: 4, color: COLORS.textSecondary, fontSize: 13, lineHeight: 18 },
  offline: { backgroundColor: COLORS.warningTint, paddingHorizontal: SPACING.md, paddingVertical: SPACING.sm, borderBottomWidth: 1, borderBottomColor: COLORS.warning },
  offlineText: { color: COLORS.text, textAlign: "center", fontSize: 12, fontWeight: "600" },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: SPACING.xs, marginTop: SPACING.sm },
  divider: { height: 1, backgroundColor: COLORS.border, marginVertical: SPACING.md },
  code: { fontFamily: "monospace", fontSize: 12, color: COLORS.text, lineHeight: 18 },
});
