export const ROUTES = {
  SPLASH: "Splash",
  LOADING: "Loading",
  LOGIN: "Login",
  REGISTER: "Register",
  FORGOT_PASSWORD: "ForgotPassword",
  ACCOUNT: "Account",

  HOME: "Home",
  ACCOUNT_TAB: "AccountTab",
  GUIDES: "Guides",
  SETTINGS: "Settings",

  AI: "AI",
  HISTORY: "History",
  INCIDENT_DETAIL: "IncidentDetail",

  FAQ: "FAQ",
  CONTACT: "Contact",
  NOTIFICATIONS: "Notifications",
  LANGUAGE: "Language",
  SAFETY_PROFILE: "SafetyProfile",
  CONSENT: "Consent",
  REGISTERED_KITS: "RegisteredKits",
  ADVANCED_SETTINGS: "AdvancedSettings",
  REGULATIONS: "Regulations",

  GUIDE_CATEGORY: "GuideCategory",
  GUIDE_DETAIL: "GuideDetail",
  APP_GUIDE_DETAIL: "AppGuideDetail",

  INCIDENT_START: "IncidentStart",
  CALL_112_GATE: "Call112Gate",
  CONTEXT_SELECTION: "ContextSelection",
  AGE_SELECTION: "AgeSelection",
  SITUATION_SELECTION: "SituationSelection",
  PROTOCOL: "Protocol",
  KIT_PREPARATION: "KitPreparation",
  VICTIMS: "Victims",
  TRIAGE: "Triage",
  SAFETY: "Safety",
  HANDOFF: "Handoff",
  INTERVIEW: "Interview",
  REPORT: "Report",
  REVIEW: "Review",

  PRACTICE_HOME: "PracticeHome",
  PRACTICE_PROTOCOL: "PracticeProtocol",
};
