import { ScrollView, Text } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import AppScreenHeader from "../../components/common/appScreenHeader/appScreenHeader";
import PrimaryCard from "../../components/common/primaryCard";
import useLocale from "../../hooks/useLocale";
import styles from "../emergency/emergencyScreen.styles";

export default function RegulationsScreen({ navigation }) {
  const { pick } = useLocale();
  return (
    <SafeAreaView style={styles.container}>
      <AppScreenHeader title={pick("Referințe și reglementări", "References and regulations")} navigation={navigation} showMenu={false} />
      <ScrollView contentContainerStyle={styles.content}>
        <Text style={styles.title}>{pick("Prim ajutor și responsabilitate", "First aid and responsibility")}</Text>
        <Text style={styles.subtitle}>{pick("Rezumat bazat exclusiv pe notițele furnizate echipei. Pentru utilizare juridică, verificați forma oficială și actualizată a actelor normative.", "Summary based only on the notes supplied to the team. For legal use, verify the official and current wording of the legislation.")}</Text>
        <PrimaryCard style={{ marginTop: 24, marginBottom: 16 }}>
          <Text style={styles.sectionTitle}>{pick("Legea 95/2006 — Titlul IV", "Law 95/2006 — Title IV")}</Text>
          <Text style={styles.protocolText}>{pick("Notițele proiectului indică faptul că primul ajutor de bază poate fi acordat de persoane instruite sau, pentru persoane fără instruire, la indicațiile personalului specializat din dispeceratele de urgență. Cazul de urgență trebuie anunțat la 112 înainte sau concomitent cu acordarea ajutorului.", "The project notes state that basic first aid may be provided by trained people or, for people without prior training, according to instructions from specialized emergency-dispatch staff. The emergency should be reported to 112 before or at the same time as first aid is given.")}</Text>
        </PrimaryCard>
        <PrimaryCard style={{ marginBottom: 16 }}>
          <Text style={styles.sectionTitle}>{pick("Ordinul 2021/691 din 12.12.2008 — notițele proiectului", "Order 2021/691 of 12 Dec 2008 — project notes")}</Text>
          <Text style={styles.protocolText}>{pick("Dacă persoanele de la locul incidentului nu au cunoștințele necesare și nu pot obține indicații, notițele recomandă îndepărtarea pericolului și evitarea manevrelor care pot agrava starea. La accidente rutiere, victimele nu se scot din vehicul decât în situații de pericol iminent descrise în document.", "If people at the scene do not have the necessary knowledge and cannot obtain specialist instructions, the notes recommend removing the danger and avoiding manoeuvres that could worsen the person's condition. In road crashes, injured people should not be removed from vehicles except in the imminent-danger situations described in the document.")}</Text>
        </PrimaryCard>
        <PrimaryCard>
          <Text style={styles.sectionTitle}>{pick("Notă de produs", "Product note")}</Text>
          <Text style={styles.muted}>{pick("Protocoalele din aplicație sunt conținut pre-scris, nu decizii medicale generate de AI. Textele marcate de documentele sursă ca necesitând validare trebuie revizuite de consultantul medical înainte de lansare.", "The app protocols are pre-written content, not medical decisions generated by AI. Text marked in the source documents as requiring validation must be reviewed by the medical consultant before release.")}</Text>
        </PrimaryCard>
      </ScrollView>
    </SafeAreaView>
  );
}
